version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:     
      - curl -sSL https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz | tar -xz -C /opt/
      - export PATH="/opt/apache-maven-3.8.4/bin:$PATH"
      - mvn --version

  build:
    commands:
      - echo "Building the Java code with Maven..."
      - mvn clean compile
      - mkdir -p webapps/WEB-INF/lib
      - cp lib/*.jar webapps/WEB-INF/lib/
      - mkdir -p webapps/WEB-INF/classes
      - cp -r target/classes/* webapps/WEB-INF/classes/

  post_build:
    commands:
      - aws s3 sync webapps s3://map-ken-wuxi-s3-test/StringConvApiGateway/

artifacts:
  files:
    - webapps/**/*
  base-directory: webapps
  discard-paths: no
